services:
  backend:
    image: lyqray/springboot-backend:2.0.6-beta
    container_name: springboot-backend
    restart: unless-stopped
    environment:
      DB_PATH: /app/data/gost.db
      JWT_SECRET: ${JWT_SECRET}
      LOG_DIR: /app/logs
      JAVA_OPTS: "-Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Shanghai"
    ports:
      - "${BACKEND_PORT}:6365"
    volumes:
      - backend_logs:/app/logs
      - sqlite_data:/app/data
    networks:
      - gost-network
    stop_grace_period: 30s
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:6365/flow/test || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    image: lyqray/vite-frontend:2.0.6-beta
    container_name: vite-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - gost-network

  # 新增 SQLite 网页管理工具
  sqlite-web:
    image: coleifer/sqlite-web
    container_name: gost-sqlite-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:8066:8080"  # sqlite-web： 默认无密码，禁止外网访问。自行设置nginx域名反对并加密访问。
    volumes:
      - sqlite_data:/data
    environment:
      - SQLITE_DATABASE=gost.db
    networks:
      - gost-network
    depends_on:
      - backend


volumes:
  sqlite_data:
    name: sqlite_data
    driver: local
  backend_logs:
    name: backend_logs
    driver: local


networks:
  gost-network:
    name: gost-network
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.66.0.0/16 
        - subnet: fd72:6666:beef::/48